=== JDimproved/JDim/xml/document.dtd
<!-- /document -->
<!ELEMENT document (history|(group|release|sentence)+)>
<!ATTLIST document header CDATA #REQUIRED>

<!ENTITY % BLOCK "asciiart|descriptions|dialog|example|list|sentence|shell|subgroup">
<!ENTITY % INLINE "icon|image|text">


<!-- asciiart -->
<!ELEMENT asciiart (#PCDATA)>
<!ATTLIST asciiart caption CDATA #IMPLIED>


<!-- descriptions -->
<!ELEMENT descriptions (item)+>
<!ATTLIST descriptions caption CDATA #IMPLIED>


<!-- dialog -->
<!ELEMENT dialog (item)+>


<!-- example -->
<!ELEMENT example (#PCDATA)>
<!ATTLIST example caption CDATA #IMPLIED>


<!-- group -->
<!ELEMENT group (%BLOCK;)+>
<!ATTLIST group header CDATA #IMPLIED>


<!-- history -->
<!ELEMENT history (year)+>
<!ATTLIST history
           version CDATA #REQUIRED
           date    CDATA #REQUIRED>


<!-- icon -->
<!ELEMENT icon EMPTY>
<!ATTLIST icon uri CDATA #REQUIRED>


<!-- image -->
<!ELEMENT image EMPTY>
<!ATTLIST image
           uri  CDATA #REQUIRED
           link CDATA #IMPLIED>

<!-- issue -->
<!ELEMENT issue EMPTY>

<!-- item -->
<!ELEMENT item (#PCDATA|%BLOCK;|%INLINE;)*>
<!ATTLIST item
           header CDATA #IMPLIED
           icon   CDATA #IMPLIED
           label  CDATA #IMPLIED
           value  CDATA #IMPLIED>

<!-- list -->
<!ELEMENT list (item)+>
<!ATTLIST list type CDATA #IMPLIED>


<!-- release -->
<!ELEMENT release (#PCDATA)>
<!ATTLIST release
           version CDATA #REQUIRED
           date    CDATA #REQUIRED>


<!-- sentence -->
<!ELEMENT sentence (#PCDATA|text)*>
<!ATTLIST sentence type CDATA #IMPLIED>


<!-- shell -->
<!ELEMENT shell (#PCDATA)>
<!ATTLIST shell caption CDATA #IMPLIED>

<!-- subgroup -->
<!ELEMENT subgroup (%BLOCK;)+>
<!ATTLIST subgroup header CDATA #IMPLIED>


<!-- text -->
<!ELEMENT text (#PCDATA)>
<!ATTLIST text link CDATA #IMPLIED>


<!-- year -->
<!ELEMENT year (#PCDATA)>

=== JDimproved/JDim/docs/xml/2008.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="history.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="更新履歴(2008年)">

<release version="2.0.0-beta080418" date="2008/04/18(金)">
お気に入りの名前変更でスペースが入力できないバグを修正
$TEXTでURLエンコードされていたバグを修正
書き込み中止のショートカットをAlt+q->Alt+wからAlt+q->Alt+qに変更
jump_new_after_reloadを有効にするとスレ再取得後に元のレスにジャンプしないバグを修正
右ボタン+ホイール回転のタブ移動で2つおきに移動するバグを修正
URLのリンクにマウスポインタを乗せた時にURLをステータスバーに表示するようにした
スレビューのテキスト上ではカーソルを I に変えるようにした
起動時にログやスレタイ検索ビューも復元するようにした(検索は再実行しない)
スレ一覧やスレビューの進むと戻るを実装
ツールバーを各ビューから独立分離した
スレ一覧、スレビューのツールバーの項目設定にロックボタンを追加
gnutlsの必須バージョンを1.2以降に変更した
インストール直後の書き込みウィンドウのフォントがスレフォントと異なるバグを修正
g++4.3対応
名前欄に b タグが二つ以上含まれたときに後ろのタグが無視されるバグを修正
ツールバー項目選択ダイアログでアイテムを追加したときに出るassertion表示を無くした
タブをドラッグ移動するときに矢印を表示するようにした
サイズの大きいスレを開こうとすると落ちる時があるバグを修正
リンクをクリックして他板のスレを開くと壊れていると判定されるバグを修正
画像ポップアップのメモリリークを修正
巨大サイズ画像を表示する時に固まったようになる問題を修正
横に細長い画像をモザイク表示すると落ちるバグを修正
jump_after_reload、jump_new_after_reloadを有効にしたとき挙動が変だったバグを修正
誤爆注意ダイアログで×ボタンでウィンドウを閉じると書き込みするバグを修正
お気に入りと混同すると指摘があったのでスレやレスの「ブックマーク」を「しおり」に改名
書き込みビューでAA入力するときに出ていたWARNINGが出ないようにした
書き込みプレビューでスペースキーなどでスクロールできない問題を修正
文字が折り返していないレスのポップアップ表示で必ずスクロールバーが付くバグを修正
埋め込み画像があるレスのポップアップ表示で必ずスクロールバーが付くバグを修正
書き込みビューをemacs風操作にするとuim環境などで誤動作する問題を修正
最大化を解除する時に時々勝手にリサイズするバグを修正
外部板を板一覧から追加/編集できるようにした
a hrefの解釈でURLが &quot;&quot; に囲まれている場合とそうでない場合で処理を分けた
起動時の引数処理を追加(既に動作中のJDにURLを渡して開ける機能など)
ボタンなど、できるだけwidgetの枠を除いて画面をすっきりさせた
サイドバーのコンボボックスを無くしてすっきりさせた
書き込みメッセージの最後がスペースか改行で終わっている場合は確認するようにした
板一覧の外部板の項目が空になった場合、etc.txtに保存されないバグを修正
一時的にDAT落ちになったスレが復活しても、お気に入りの表示のアイコンが戻らないバグを修正
ツールバーに埋め込んでいたScrolledWindowをHBoxに変更した
レスポップアップの最大幅をスレビューの幅に制限するようにした
「表示→詳細設定→一般→ボタンをフラット表示」を追加
</release>

<release version="2.0.0-beta080601" date="2008/06/01(日)">
簡易実況モード追加( ショートカット = F6 )
スムーススクロール時のカクカクを軽減(描画タイマーを通常描画と別にした)
ツールバーとしてGtk::Toolbarをカスタマイズして使用する事にした
各ビューと枠との間の余白を設定できるようにした( view_margin )
高速スクロールの速度調整設定追加( key_fastscroll_size )
書き込みメッセージのスペース/改行チェックの実装を取りやめた
画像ビューの拡大縮小でテンキーの「+-」も使えるようにした
多重ポップアップの際にポップアップの最大幅が1つ前の参照元の幅になっていたのを修正
スレタイ検索で数字選択してポップアップさせると落ちるバグを修正
スレタイ検索でキーワード抽出などをすると落ちるバグを修正
効果音再生機能を実装( ./configure --with-alsa )
スレ読み込み中にビューを閉じると落ちる時があるバグを修正
スレビューのダブル、トリプルクリックによる範囲選択機能を強化
</release>

<release version="2.0.0-beta080702" date="2008/07/02(水)">
「前回開いていた各ビューを起動時に復元する」のチェックを外してもロックしていたタブを復元
about:config 実装
キャッシュが無く、かつdat落ちしているスレを2回開いたときにタブが空白になるバグを修正
自分の書き込みを抽出できるようにした。
HRタグ実装
スレビューの埋め込み画像の枠の下部が表示されないときがあるバグを修正
スクロール時の埋め込み画像の表示を高速化
書き込みログを一覧表示できるようにした(ツールメニューから)
書き込みログが最大サイズ(バイト)を越えたら分割するようにした(about:configでバイト設定)
自分の書き込んだレスにマークをつけることができるようにした(表示の詳細設定から)
自分の書き込みに対するレスにマークをつけることができるようにした(表示の詳細設定から)
スレビューのしおりをアイコン表示に変更
板一覧のコメントの文字色を設定できるようにした(色の詳細設定から)
色の詳細設定にリセットボタンを追加
</release>

<release version="2.0.0-rc080714" date="2008/07/14(月)">
検索バーをescapeで閉じるようにした。
非表示の状態からサイドバーをドラッグして表示させるとXの閉じるボタンを押しても閉じないバグを修正
画像と書き込みビューを埋め込み表示にすると画像を表示した時に書き込みツールバーが現れるバグを修正
書き込みプレビューボタンをトグルキーにした
自動板移転処理後に板一覧を更新すると自動移転処理できなくなるバグを修正
板のプロパティに更新日時の表示とリセットを追加
書き込みビューが画面の下側にあるときにAAポップアップの表示領域を広げた
お気に入り登録ダイアログをqやESCキーで閉じられるようにした
テーマによってはツールバーが描画されないバグを修正
compiz環境で起動する度にウィンドウが右下にずれていくバグを修正
gtkrcを利用してツリービューの背景色を描画する時に偶数行が描画されないバグを修正
</release>

<release version="2.0.0-080722" date="2008/07/22(火)">
閉じるボタンを押してビューを閉じた後に再び開くとボタンの枠が表示されたままになるバグを修正
テンキーの「Home」や「Pg Dn」などでも操作出来るようにした
about:configに「自前でウィンドウ配置を管理する」を追加
</release>

<release version="2.0.1-beta080901" date="2008/09/01(月)">
ユーザコマンドのGUI設定と階層化を実装
jd.confのget_max_show_usrcmdを廃止
板移転時に落ちるときがあるバグを修正
他スレポップアップ時に落ちる時があるバグを修正
ダウンロードしたファイルが画像でないときに Content-Typeを表示するようにした
起動中にスレビューの余白の上でマウスを動かすと落ちるときがあるバグを修正
Auroraなどの特定のテーマでスレ一覧のスクロールバーが描画されない時があるバグを修正
リンクフィルタ機能実装
スレ一覧で前回開いた時点以降に立てられたスレをアイコン表示するようにした
about:configに「お気に入りでカテゴリを常にひとつだけ開く」を追加
スレのプロパティに更新日時のクリアボタンを追加
ubuntuなど環境によってはプロパティの更新日時表示が正しくなかったバグを修正
レスの引用コピーでアドレスもコピーするようにした。
書き込みビューに長い文章をコピペすると落ちるバグを修正
書き込みビューで改行や特殊文字の文字数を考慮するようにした
key.confでExecWrite = Shift+Enterとして書き込みをすると改行が入るバグを修正
スレビューの検索、スレ一覧、板一覧の検索の補完記録を分離した
about:configに「3ペーン時にスレ一覧やスレビューを最大化する」を追加
ユーザコマンドにBBSNAME,DATNAME,HOST,HOSTL,TITLE,BOARDNAME,LOGPATH,NUMBER 追加
ユーザコマンドにCACHEDIMG,DIALOG,ONLY 追加
ユーザコマンドにTEXTI, TEXTIU, TEXTIX, TEXTIE, INPUT, INPUTU, INPUTX, INPUTE 追加
外部ブラウザを用いてp2経由で書き込む機能を実装
画像ダウンロード時にリダイレクトが起きると反応が無くなる時があるバグを修正
2chログイン中は書き込み秒数規制をしないようにした
スレビューや画像ビューでエラー画像のエラーコードも削除できるようにした
まちBBSでread.cgi形式のアドレス表記に対応した
多重ポップアップに移行するときフォーカスが外れるとポップアップが閉じるバグを修正
BEにログインしているときは書き込み規制秒数ダイアログを表示しないようにした
solarisでもソースの修正無しでコンパイルが通るようにした
</release>

<release version="2.0.1-080914" date="2008/09/14(日)">
デフォルトフォントにMona-VLGothicを追加
セットアップウィザードにペイン設定を追加
スレ削除、板移転確認ダイアログに「表示しない」のチェックボタンを追加
configureのオプションに「--with-xdgopen」を追加
configureのオプションに「--with-atom」を追加
</release>

<release version="2.0.2-080919" date="2008/09/19(金)">
書き込み時にhana=mogeraやsuka=pontanの様なキーワードをきちんと取得するようにした
レス中の「&lt;hr&gt;」にスキンが適用されていなかったバグを修正
</release>

<release version="2.0.3-beta081110" date="2008/11/10(月)">
書き込みビューでTabキーで書き込みボタンがフォーカスされなかったバグを修正
configureのオプションに「--with-ppc74x0」オプションを追加
gtkmm-2.4 でコンパイルが通るようにした
uimの文字変換中にCtrl+qを押すとキーアクセレートが優先されてJDが終了するバグを修正
boards.xmlの中に同じ板のアドレスが多重登録されていると起動時に落ちるバグを修正
FreeBSDの場合はtimegmの代わりにmktimeを使うようにした。
board.infoが空ファイルの時に落ちるバグを修正
復元しない設定で画像ビューを開いたまま閉じると再起動時に画像ビューが表示されるバグを修正
モザイクのかけ具合をabout:configで調整できるようにした。
vip2chの読み書きに対応した
ショートカットキー設定をGUI化した
マウスジェスチャ設定をGUI化した
ボタン設定をGUI化した
Beログイン時にBeアイコンが表示されるため自分の書き込みの判定に失敗するバグを修正
Beアイコンを表示出来るようにした
アクセシビリティをonにすると画像削除でフリーズするバグを修正
navi2ch互換スレ情報ファイルが壊れているとJDが落ちるバグを修正
スレのプロパティに書き込み履歴クリアボタンを追加
板のプロパティに板内の全スレの書き込み履歴クリアボタンを追加
プライバシー情報の削除に書き込みログの削除と書き込み履歴削除を追加
スレビューが縦に非常に長い時に下の方にあるリンクがクリック不可になるバグを修正
設定メニューに書き込み履歴(鉛筆マーク)を保存しない設定を追加
サイドバーのツールバーに「お気に入り更新チェックボタン」を追加出きるようにした
色の詳細設定を表形式にした
画像ビューで画像サイズをウィンドウの横幅のみに合わせられるモードを追加(xキーでモード切り替え)
BASIC認証有りの外部板のSETTING.txtとhead.txtのロード時も認証するようにした
</release>

<release version="2.0.3-rc081117" date="2008/11/17(月)">
「ここまで読んだ」が表示されていると「リロード後に新着レスに自動的に移動」が効かない問題を修正
gcc4.4対応
更新チェック時にスレビューのタブのアイコンが正しく更新されない時があるバグを修正
</release>

<release version="2.0.3-081124" date="2008/11/24(月)">
書き込み履歴を削除したときに、固定書き込み名とメールも消去するようにした。
</release>

<release version="2.1.0-beta081216" date="2008/12/16(火)">
次スレ検索機能を実装
次スレ移行時にお気に入りの名前とアドレスも更新するようにした
お気に入りビューの更新マークを再起動しても消えないようにした
お気に入り項目の編集直後に板かスレを開いたときにお気に入りの状態を保存するようにした
proxyのbasic認証に対応した
お気に入り挿入先の選択ダイアログを作り直した
お気に入りのショートカット(Ctrl+d)追加
スレビューで適当なダイアログを開いて閉じた後にスクロールが変になるバグを修正
書き込みログ表示で再読み込みをすると空白のビューが表示されるバグを修正
板一覧の読み込みに失敗した時にダイアログを表示するようにした
お気に入りで空白行にもコメントを入れられるようにした
お気に入り編集ウィンドウを作成( ツールメニューに「お気に入りの編集」を追加 )
適当にやっていたDnD処理をきちんと作り直した
ダイアログ上でスレッドからのメッセージがDispatchされない問題をタイマーを使って解決した
squid3経由でスレを差分ダウンロードするとtimeoutする問題を解決(Content-Lengthを考慮した)
スレの差分ダウンロード時にプロキシがrangeを無視して先頭からdatを送って来る場合に対処
</release>

<release version="2.1.0-081228" date="2008/12/28(日)">
動作環境にconfigureオプションを表示するようにした
「JDについて」のダイアログに動作環境を追加した
鬼車を使用可能にした( ./configure --with-oniguruma )
ユーザープロフィールの様に途中でhttp://が入っているアドレスが板として認識されるバグを修正
次スレ検索時にしおりが付いているスレの次スレにもしおりを付けるようにした
about:configに「スレをお気に入りに追加した時にしおりをセットする」設定を追加
お気に入りに登録されているスレのキャッシュを削除した時にお気に入りも削除するようにした
ログアウト時にタイミングによってjd.confが壊れるバグを修正
プロキシのホスト名にhttp://などが付いているとロード出来ないバグを修正
実況等で書き込みと読み込みのタイミングによって書き込み判定に失敗するバグを修正
一行目の改行前にスペースを沢山入れた書き込みの書き込み判定に失敗するバグを修正
</release>

</document>

=== JDimproved/JDim/docs/xml/skin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="テーマについて">


<group header="スタイルシート設定 (jd.css)">
  <sentence>
  スタイルシートはテーマフォルダ(デフォルトでは~/.jd/theme)を作成し、その中に「jd.css」
  という名前のファイルを作って設定する。
  </sentence>

  <subgroup header="対応しているプロバティ">
    <descriptions>
      <item header="color">文字色: リンクなどJDの設定メニューから設定する物を除く</item>
      <item header="background-color">背景色:</item>
      <item header="border-color">枠線色: border-left-color など個別指定も可能</item>
      <item header="border-style">枠線形: solid のみに対応</item>
      <item header="border-width">枠線幅: border-left-width など個別指定も可能</item>
      <item header="margin">外余白: margin-left など個別指定も可能</item>
      <item header="padding">内余白: padding-left など個別指定も可能 </item>
      <item header="text-align">位置: left, center, right のみに対応</item>
    </descriptions>
  </subgroup>

  <subgroup header="色の指定方法">
    <sentence>
    blackやwhiteなどの定義済み色名か「#RRGGBB」形式で指定する。定義済み
    色名の種類は次の通り。
    </sentence>

    <list type="circle">
      <item>red</item>
      <item>fuchsia</item>
      <item>purple</item>
      <item>maroon</item>
      <item>yellow</item>
      <item>lime</item>
      <item>green</item>
      <item>olive</item>
      <item>blue</item>
      <item>aqua</item>
      <item>teal</item>
      <item>navy</item>
      <item>white</item>
      <item>silver</item>
      <item>gray</item>
      <item>black</item>
      </list>
  </subgroup>

  <subgroup header="単位">
    <sentence>px, em のみに対応。単位を省略すると px になる。</sentence>
  </subgroup>

  <subgroup header="レスの構造">
    <sentence>
    スレ内のひとつひとつのレスは以下のような構造となっている。NUMBERやNA
    MEなどの要素については「レス構造設定」の項で説明する。
    </sentence>

<example>
&lt;div class=&quot;res&quot;&gt;
&lt;div class=&quot;title&quot;&gt;&lt;NUMBER/&gt; &lt;NAMELINK/&gt;：&lt;NAME/&gt; &lt;MAIL/&gt;： &lt;DATE/&gt; &lt;ID/&gt;&lt;/div&gt;
&lt;div class=&quot;mes&quot;&gt;&lt;MESSAGE/&gt;&lt;IMAGE/&gt;&lt;/div&gt;
&lt;/div&gt;
</example>
  </subgroup>

  <subgroup header="定義済みのセレクタ">
    <sentence>
    注意: jd.css でクラス指定する際は div.res{} と書かずに .res{} と要素
    名(div)を書かずにクラス名だけを指定すること。
    </sentence>

    <descriptions>
      <item header="body">スレビューのbody要素</item>
      <item header=".res">ひとつのレスの要素</item>
      <item header=".title">ひとつのレスのヘッダ行</item>
      <item header=".mes">ひとつのレスの本文</item>
      <item header=".separator">ここまで読んだ。&lt;div class=&quot;separator&quot;&gt;ここまで読んだ&lt;/div&gt; という構造になっている。</item>
      <item header=".comment">コメントブロック。&lt;div class=&quot;comment&quot;&gt;任意のコメント&lt;/div&gt; という構造になっている。</item>
      <item header="imgpopup">画像ポップアップのbody要素。color, background-color, border-color, border-width, margin プロバティのみ(単位はpxのみ)に対応。</item>
    </descriptions>
  </subgroup>
</group>


<group header="レス構造設定 (Res.html)">
  <sentence>
  スレ内のひとつひとつのレスは「スタイルシート指定」の「定義済み要素、ク
  ラス」の項で示した構造となっている。この構造をテーマフォルダ(デフ
  ォルトでは~/.jd/theme)の中にRes.htmlという名前のファイルを作って指定すること
  が出来る。
  </sentence>

  <subgroup header="使用可能な要素">
    <sentence>&lt;div&gt; のみ</sentence>
  </subgroup>

  <subgroup header="置換可能な定義済み要素">
    <sentence>
    Res.htmlでは次のように定義済み要素を指定して文字列の置換ができる。
    </sentence>

    <descriptions type="option" summary="置換可能な定義済み要素">
      <item header="&lt;NUMBER/&gt;">レス番号</item>
      <item header="&lt;NAMELINK/&gt;">名前メニュー表示のリンク。「名前」の文字列に置換される。</item>
      <item header="&lt;NAME/&gt;">名前</item>
      <item header="&lt;MAIL/&gt;">メール</item>
      <item header="&lt;DATE/&gt;">日付</item>
      <item header="&lt;ID/&gt;">ID</item>
      <item header="&lt;MESSAGE/&gt;">本文。「br=&quot;no&quot;」属性を指定すると本文の改行をしない。</item>
      <item header="&lt;IMAGE/&gt;">インライン画像</item>
    </descriptions>
  </subgroup>

  <subgroup header="注意点">
    <list type="decimal">
      <item>
      &lt;div class=&quot;res&quot;&gt;〜&lt;/div&gt;はRes.htmlで指定する
      必要が無い。つまり Res.htmlに&quot;hoge&quot;とだけ指定した場合、レ
      スの構造は以下のようになる。
<example>
&lt;div class=&quot;res&quot;&gt;
hoge
&lt;/div&gt;
</example>
      </item>
      <item>div の中に divを配置することは出来ない( 上の &lt;div class=&quot;res&quot;&gt;は例外 )。</item>
      <item>クラス名は定義済みの物だけではなくて自由に指定できる。</item>
    </list>
  </subgroup>
</group>

<group header="アイコン設定">
  <sentence>
   アイコンテーマのフォルダ(デフォルトでは ~/.jd/theme/icons )に
   対応するアイコン画像を置くとJDのアイコンが置き換わる。
   </sentence>

  <subgroup header="">
    <list type="decimal">
   <item>画像形式は一般的な物なら大体使用可能 ( png, jpg, svg, gif, bmp, その他)</item>
   <item>画像サイズは任意のサイズで良い( 16x16 がデフォルトサイズ)</item>
   <item>ファイル名は「アイコン名.拡張子 」(例) reload.jpg、 quit.png</item>
   <item>ファイル名の一覧はsvnにある<text link="http://sourceforge.jp/projects/jd4linux/svn/view/jd/trunk/src/icons/iconfiles.h?view=markup&amp;root=jd4linux">ヘッダファイル(iconfiles.h)</text>を参照すること</item>
   </list>
  </subgroup>
</group>

<group header="使用例">
  <sentence>
    <image link="image/skin_sample.png" uri="image/skin_sample_thumb.png" text="スキンサンプル" />
    クリックで拡大
  </sentence>

  <sentence>Res.html(下)と<text link="jd.css">jd.css</text></sentence>

<example>
&lt;div class=&quot;title&quot;&gt;&lt;NUMBER/&gt; &lt;NAMELINK/&gt;：&lt;NAME/&gt; &lt;MAIL/&gt;&lt;/div&gt;
&lt;div class=&quot;mes&quot;&gt;&lt;MESSAGE/&gt;&lt;IMAGE/&gt;&lt;/div&gt;
&lt;div class=&quot;id&quot;&gt;&lt;ID/&gt;&lt;/div&gt;
&lt;div class=&quot;date&quot;&gt;&lt;DATE/&gt;&lt;/div&gt;
</example>
</group>


</document>

=== JDimproved/JDim/docs/xml/info.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="その他">


<group>
  <list type="circle">
    <item><text link="move.xml">板移転について</text></item>
    <item><text link="http://sourceforge.jp/projects/jd4linux/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E8%A8%AD%E5%AE%9A%E9%9B%86">ユーザーコマンド設定集</text> (wiki)</item>
    <item><text link="skin.xml">テーマについて</text></item>
    <item><text link="environment.xml">動作環境の記入について</text></item>
    <item><text link="sound.xml">効果音の再生について</text></item>
    <item><text link="urlreplace.xml">URL変換について</text></item>
  </list>
</group>


</document>

=== JDimproved/JDim/xml/make.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="make、実行方法について">


<group header="動作環境">
  <subgroup header="必須環境">
    <list type="circle">
      <item>gtkmm-2.4.8 以上</item>
      <item>zlib-1.2 以上</item>
      <item>gnutls-1.2 以上</item>
    </list>
  </subgroup>

  <subgroup header="推奨環境">
    <list type="circle">
      <item>Linux Kernel 2.6以上</item>
      <item>gtkmm-2.8以上 ( 2.6より低いとレイアウトが一部崩れる、2.8より低いとスレ一覧表示が遅い )</item>
      <item>UTF-8環境 ( EUC環境では LANG=&quot;ja_JP.UTF-8&quot; を指定する必要がある )</item>
    </list>
  </subgroup>
</group>


<group header="makeに必要なツール、ライブラリ">
  <subgroup header="必須">
    <list type="circle">
      <item>autoconf</item>
      <item>automake</item>
      <item>g++</item>
      <item>gnutls</item>
      <item>gtkmm</item>
      <item>libtool</item>
      <item>make</item>
      <item>zlib</item>
    </list>
  </subgroup>

  <subgroup header="オプション">
    <list type="circle">
      <item>alsa-lib (--with-alsa)</item>
      <item>libgnomeui (--with-sessionlib=gnomeui)</item>
      <item>openssl (--with-openssl)</item>
      <item>oniguruma (--with-oniguruma)</item>
      <item>libpcre (--with-pcre)</item>
    </list>
  </subgroup>

  <sentence>
  OSやディストリビューション別の解説は<text link="http://sourceforge.jp/projects/jd4linux/wiki/OS%2f%E3%83%87%E3%82%A3%E3%82%B9%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E5%88%A5%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%96%B9%E6%B3%95">OS/ディストリビューション別インストール方法</text> (wiki) を参照。
  </sentence>
</group>


<group header="make 方法( rpmbuild の場合 )">
  <list type="decimal">
    <item>rpmbuild -tb 〜.tgz でrpmファイルが出来るのであとは rpm -Uvh 〜.rpm</item>
    <item>ライブラリが足りないといわれたら yum install 〜-devel</item>
    <item>起動はメニューから起動するか、端末で jd と打ち込んでエンターを押す。</item>
  </list>
</group>


<group header="make 方法( configure + make の場合 )">
  <list type="decimal">
    <item>autoreconf -i ( 又は ./autogen.sh )</item>
    <item>./configure</item>
    <item>make</item>
    <item>(お好みで) strip src/jd</item>
  </list>
</group>


<group header="configureオプション">
  <descriptions>
    <item header="--with-sessionlib=[xsmp|gnomeui|no]">
    GNOMEUIを使ってセッション管理をするには「gnomeui」を、セッション管理
    を無効にするには「no」を選択。デフォルトでは XSMPを使用する。
    </item>
    <item header="--with-pangolayout">
    描画にPangoLayoutを使う。デフォルトでは PangoGlyphString を使用する。
    </item>
    <item header="--with-migemo">
    migemoによる検索が有効になる。migemoがUTF-8の辞書でインストールされている必要がある。
    </item>
    <item header="--with-[native|core2duo|athlon64|atom|ppc7400|ppc7450]">
    CPUに合わせた最適化
    </item>
    <item header="--with-openssl">
    GNU TLSではなく OpenSSLを使用する。ライセンス上バイナリ配布が出来なくなることに注意すること。
    </item>
    <item header="--with-alsa">
    ALSAによる効果音再生機能を有効にする。
    詳しくは<text link="sound.xml">効果音の再生</text>の項を参照すること。
    </item>
    <item header="--with-xdgopen">
    デフォルトブラウザとしてxdg-openを使用する。
    </item>
    <item header="--enable-gprof">
    gprofによるプロファイリングを行う。
    コンパイルオプションに -pg が付き、JDを実行すると gmon.out が出来るので
    gprof  ./jd  gmon.out で解析できる。CPUの最適化は効かなくなるので注意する。
    </item>
    <item header="--with-oniguruma">
    正規表現ライブラリとしてPOSIX regex の代わりに鬼車を使用する。鬼車はBSDライセンスなのでJDをバイナリ配布する場合には注意すること(ライセンスはGPLになる)。
    </item>
    <item header="--with-pcre">
    正規表現ライブラリとしてPOSIX regex の代わりにPCREを使用する。PCREはBSDライセンスなのでJDをバイナリ配布する場合には注意すること(ライセンスはGPLになる)。
    UTF-8が有効な ( --enable-utf オプションを用いて make する ) PCRE 6.5 以降が必要となる。
    Perl互換の正規表現なので、従来の POSIX 拡張の正規表現から設定変更が必要になる場合がある。
    </item>
    <item header="--with-gthread">
    pthreadの代わりにgthreadを使用する。
    </item>
  </descriptions>
</group>


<group header="メモ">
  <sentence>
  最近のディストリビューションの場合は autogen.sh よりも autoreconf -i の方を推奨。
  </sentence>

  <sentence>
  実行するには直接 src/jd を起動するか手動で /usr/bin あたりに src/jd を cp する。
  </sentence>

  <sentence>
  以上の操作でmakeが通らなかったり動作が変な時は configure のオプションを変更する。
  </sentence>
</group>


</document>

=== JDimproved/JDim/docs/xml/asciiart.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="アスキーアート(AA)の入力について">


<group header="操作方法">
  <sentence>
  書き込みビューでアスキーアート(AA)メニューを表示してAAを入力することが
  できる。
  </sentence>

  <descriptions>
    <item header="Alt+a">AAメニューを表示</item>
    <item header="↑、j, Ctrl+p">選択項目を上に移動</item>
    <item header="↓、k, Ctrl+n, space">選択項目を下に移動</item>
    <item header="Enter">決定</item>
    <item header="Esc">キャンセル</item>
  </descriptions>

  <sentence>
  なお、AAメニューの左側の[]の内部にある文字はキーボードショートカットを
  表していて、キーを押すと対応するAAが入力される(数字→英小文字→英大文字の順にキーが割り当てられる。
  ただし h,i,j,k は除く )。
  </sentence>
</group>


<group header="登録方法">
  <sentence>
  AAはキャッシュディレクトリ(デフォルトでは~/.jd/)にaalist.txtというテキ
  ストファイルを作成して登録する。
  </sentence>

  <sentence>一行AAはそのままaalist.txtの各行に登録する。</sentence>

  <sentence>
  複数行AAはキャッシュディレクトリに「aa」というディレクトリを作成し、そ
  の下に複数行AAを保存したテキストファイル(*.txt)をおき、aalist.txtに
  「*ファイル名」という形式で登録する。なお拡張子(.txt)は省略することが
  出来る。なお先頭のアスタリスクを「**」と2つつなげるとファイル名ではなく
  て文字の「*」一文字に変換される。
  </sentence>

<asciiart caption="aalist.txt 登録例">
ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━ !!
*mona
</asciiart>

<asciiart caption="~/.jd/aa/mona.txtの内容">
　 ∧＿∧
　（　´∀｀）
　（　　　　）
　｜　|　 |
　（＿_)＿）
</asciiart>
</group>


</document>

=== JDimproved/JDim/docs/xml/live.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="実況モードについて">


<group header="開始と停止方法">
  <sentence>
  デフォルトでは実況モードは使用出来ないようになっている。実況したい板の
  プロパティを開いて「実況する」をチェックすることで実況可能になる。
  </sentence>

  <sentence>
  実況可能にしたら、ツールメニューから実況サブメニューを選択するか、スレ
  ビュー上でF6キーを押すか、表示設定からスレビューのツールバーに実況ボタ
  ンを表示させてから実況ボタンをクリックすると実況が始まる。再び実況サブ
  メニューを選択するか、F6キーを押すか、実況ボタンをクリックするか、スレ
  ビューの適当な場所をクリックすると停止する。
  </sentence>
</group>


<group header="更新間隔">
  <sentence>
  更新間隔は各板別に板のプロパティで設定する。最低更新間隔は 10 秒で、更
  新が無い場合は間隔が5秒ずつ増えて行く。5回更新が無いときは停止する。
  </sentence>
</group>


<group header="オートスクロール">
  <sentence>
  オートスクロールの速度などは全板共通でメニューの「設定」→「その他」→
  「実況設定」から設定する。スクロールモードには「スクロール速度を実況速
  度に合わせて可変させるモード」「常に一定速度でスクロールさせるモード」
  の二通りある。スクロール速度/実況遅れが設定したしきい値を越えると行単
  位でのスクロールに切り替わる。
  </sentence>
  <sentence>
  マウスオンなどでポップアップを表示している間は、オートスクロールを一時停止する。
  </sentence>
</group>


<group header="書き込みビューについて">
  <sentence>
  書き込みビューが表示されているときは書き込みビューが常にフォーカスされ
  る。書き込みビューを埋め込み表示にして「書き込み後に閉じない」ボタンを
  押して使うと実況向けとなる。
  </sentence>
</group>


<group header="実況終了スレの自動削除">
  <sentence>
  実況状態のまま閉じたスレはJD終了時に自動でログを削除する。削除をキャン
  セルするには実況を停止してからスレを閉じるか、もう一度スレを開く(ただ
  し実況モードにはしない)。なお、スレ一覧でしおりをつけたスレや、スレビ
  ューで任意のレスにひとつでもしおりをつけたスレは削除しない。 
  </sentence>
</group>


</document>
