=== JDimproved/JDim/xml/document.dtd
<!-- /document -->
<!ELEMENT document (history|(group|release|sentence)+)>
<!ATTLIST document header CDATA #REQUIRED>

<!ENTITY % BLOCK "asciiart|descriptions|dialog|example|list|sentence|shell|subgroup">
<!ENTITY % INLINE "icon|image|text">


<!-- asciiart -->
<!ELEMENT asciiart (#PCDATA)>
<!ATTLIST asciiart caption CDATA #IMPLIED>


<!-- descriptions -->
<!ELEMENT descriptions (item)+>
<!ATTLIST descriptions caption CDATA #IMPLIED>


<!-- dialog -->
<!ELEMENT dialog (item)+>


<!-- example -->
<!ELEMENT example (#PCDATA)>
<!ATTLIST example caption CDATA #IMPLIED>


<!-- group -->
<!ELEMENT group (%BLOCK;)+>
<!ATTLIST group header CDATA #IMPLIED>


<!-- history -->
<!ELEMENT history (year)+>
<!ATTLIST history
           version CDATA #REQUIRED
           date    CDATA #REQUIRED>


<!-- icon -->
<!ELEMENT icon EMPTY>
<!ATTLIST icon uri CDATA #REQUIRED>


<!-- image -->
<!ELEMENT image EMPTY>
<!ATTLIST image
           uri  CDATA #REQUIRED
           link CDATA #IMPLIED>

<!-- issue -->
<!ELEMENT issue EMPTY>

<!-- item -->
<!ELEMENT item (#PCDATA|%BLOCK;|%INLINE;)*>
<!ATTLIST item
           header CDATA #IMPLIED
           icon   CDATA #IMPLIED
           label  CDATA #IMPLIED
           value  CDATA #IMPLIED>

<!-- list -->
<!ELEMENT list (item)+>
<!ATTLIST list type CDATA #IMPLIED>


<!-- release -->
<!ELEMENT release (#PCDATA)>
<!ATTLIST release
           version CDATA #REQUIRED
           date    CDATA #REQUIRED>


<!-- sentence -->
<!ELEMENT sentence (#PCDATA|text)*>
<!ATTLIST sentence type CDATA #IMPLIED>


<!-- shell -->
<!ELEMENT shell (#PCDATA)>
<!ATTLIST shell caption CDATA #IMPLIED>

<!-- subgroup -->
<!ELEMENT subgroup (%BLOCK;)+>
<!ATTLIST subgroup header CDATA #IMPLIED>


<!-- text -->
<!ELEMENT text (#PCDATA)>
<!ATTLIST text link CDATA #IMPLIED>


<!-- year -->
<!ELEMENT year (#PCDATA)>

=== JDimproved/JDim/xml/2007.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="history.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="更新履歴(2007年)">

<release version="1.8.5-beta070114" date="2007/01/14(日)">
生のdatファイルに\0などの制御文字が含まれていると表示が壊れるバグを修正
スレ一覧のマークでのソーティングアルゴリズムを変更
キャッシュのログ検索を暫定的に実装
ツールバーにサイドバーの切り替えボタンを付けた
移転処理した時に移転した板を表示するダイアログでTextViewを使用した
移転処理をしたときにSETTING.TXTをロードしなくなる時があるバグを修正
移転したときに履歴メニューのURLが変更されていなかったバグを修正
外部板ビューを廃止して外部板は板一覧の先頭に表示するようにした
板一覧とお気に入りをサイドバー形式に変更
スレ一覧、スレ表示、画像タブを廃止
ビュー切り替えボタンをツールバーに追加
ツールバーの位置を切り替えられるようにした
書き込み時のデフォルトの名前とメールアドレスを板別に設定できるようにした
書き込みビューにundoボタンを付けた
画像ビューでキーボードでスクロール出来るようにした
チルトボタンの設定を button.conf に追加
</release>

<release version="1.8.5-rc070121" date="2007/01/21(日)">
書き込みビューでCtrl+n,pでカーソルを移動した時にスクロールしないバグを修正
書き込みプレビューで画像をダウンロードしてもリンクの色が変わらないバグを修正
書き込みプレビューで画像を削除してもリンクの色が変わらないバグを修正
設定メニューに「書き込みビューでEmacs風のキーバインドにする」の項目を追加
2.4以下のgtkmmでスピンボックスの値が変わらなかったバグを修正
板一覧とお気に入りをコンボボックスで切り替えられるようにした
ツリービューの背景色設定にgtkrcを用いる設定を追加( use_tree_gtkrc )
画像ビューを開かないようにする設定を追加( use_image_view )
選択不可のユーザコマンドを非表示にする設定追加( hide_usrcmd )
指定した数( max_show_usrcmd )以上の時はサブメニュー表示にする設定追加
</release>

<release version="1.8.5-070203" date="2007/02/03(土)">
参照文字に&amp;yen;追加
スレ一覧を全部閉じてから板一覧を閉じてもスレにフォーカスが移らないバグを修正
初回起動時に板一覧ではなくてお気に入りにフォーカスがあるバグを修正
ビューの切り替え方法を説明したダイアログを表示するようにした
移転情報テーブルが循環しているとお気に入りのアドレスが空白になるバグを修正
</release>

<release version="1.8.8-beta070218" date="2007/02/18(日)">
表示されていないビューの切り替えボタンやメニューは非アクティブにした
「選択範囲を引用してレス」を右クリックメニューに追加
2pane, 3paneモードの切り替えなどを再起動無しでできるようにした
ツールバーの位置を再起動無しで切り替えられるようにした
複数のスレを表示しているときにウィンドウのリサイズを高速化
3pane表示のときに開いていないビューを隠すようにした
埋め込み書き込みビュー実装
画像ウィンドウ分離表示機能実装
板移転時にメッセージのjavascriptを解析して移転情報を更新する機能を実装
ユーザコマンドに$DATURLと$LOCALDATを追加
http://info.2ch.net を板として認識していたバグを修正
idpopup_by_mo, refpopup_by_mo,namepopup_by_mo 設定追加
名前欄のbタグで囲まれたトリップなどの文字列に色を付けられるようにした( thank to tamagodake氏)
</release>

<release version="1.8.8-beta070317" date="2007/03/17(土)">
ヘルプファイルをXML化した( thank to tamagodake氏)
フォント、色詳細設定ダイアログ追加( thank to tamagodake氏)
スレ一覧の速度の計算アルゴリズムを変えた
Debian GNU/kFreeBSD に configure.inを対応した
ダイアログボックスのフォーカス処理をきちんとするようにした
書き込みビューを開いているときにスレビューの「レス」「参照してレス」、および「引用してレス」
を選択すると書き込みビューに引用できるようにした( thank to tamagodake氏)
書き込みビューに「書き込み後に閉じない」ボタン追加
メニュー項目の見直しと整理
utf8環境で起動していないときは警告を出すようにした( thank to tamagodake氏)
メニューバーの表示設定追加(F8)
スレビューでのホイールスクロール速度設定追加( jd.confのscroll_size )
RFC規定外の文字(^など)もURL判定に用いる設定追加( jd.confのloose_url)
ロックファイルにPIDを保存して起動済み判定を厳密にした
書き込みビューのタブを取り除いてプレビューボタンを追加した
ローダ実行中にあるタイミングで別のローダを起動すると落ちるバグを修正( class Dispatchable 追加 )
ツリービューの行間スペース設定追加( jd.confのtree_ypad )
書き込み先がスレビューで開いているスレと異なるときは警告を出すようにした
ツリービューのハイライト色の設定追加
make時にx86_64で警告が出る問題を修正( thanks to 180氏)
ipv6使用オプション追加( jd.confのuse_ipv6)
書き込みビューにファイル挿入ボタン追加
</release>

<release version="1.8.8-beta070324" date="2007/03/24(土)">
画像ウィンドウ表示時に画像の参照元レスを開いてもウィンドウが閉じないバグを修正
画像ウィンドウ表示時にマウスジェスチャが表示されないバグを修正
画像ウインドウが表示される前にqを連打してウィンドウを閉じると落ちるバグを修正
KDE環境で画像ウィンドウ上でダイアログを閉じるとフォーカスが外れるバグを修正
GIF画像の読み込みに失敗すると落ちるバグを修正
強制画像再読み込みをしてもアイコン表示が変わらないバグを修正
埋め込み書き込みビューがフォーカスされてもURLとタイトルが変わらないバグを修正
埋め込み書き込みビューを開いたまま再起動するとフォーカスが外れるバグを修正
スレ一覧の読み込み中にスレを読んでいると読み込み終了時にスレ一覧に戻るバグを修正
スレビューにフォーカスがあるときはスレビューをクリックしても再描画をかけないようにした
AAポップアップメニューにAAが表示されないときがあるバグを修正
セットアップウィザード追加
初起動直後の初期フォントをシステムで利用可能な物から選ぶようにした
</release>

<release version="1.8.8-rc070330" date="2007/03/30(金)">
移転処理時にスレビューに対象板内のスレを開いていると再読み込み出来なくなるバグを修正
書き込みプレビュー画面でCtrl+g(検索)を押すと落ちるバグを修正
フォントの詳細設定ダイアログに行高さ調整の項目追加
フォントの詳細設定ダイアログに下線位置調整の項目追加
書き込みエディタの文字や背景色を変更できるようにした
スレビューでShift+キーにスクロール機能を割り当てると2回スクロールするバグを修正
細かいバグの修正
その他微調整
</release>

<release version="1.8.8-070403" date="2007/04/03(火)">
スレタイトルに特殊文字が入っているときにデコードされてなかったバグを応急処置で修正
</release>

<release version="1.9.5-beta070516" date="2007/05/16(水)">
スレビューの描画エンジンを最適化
新着しおり(ここまで読んだ)をブロック要素化
css対応( jd.css )
画像表示関係を高速化
レススキン対応( Res.html )
インライン画像実装
インライン画像のon/off設定をメニューに追加
お気に入りが空のとき最後に移動すると異常終了するバグを修正
板レベルのあぼーん設定を追加
画像キャッシュクリアを高速化
画像キャッシュ削除中にダイアログを出してキャンセル可能にした
画像プロパティにサイズやキャッシュ保護のチェックなどを追加
スレッドのデフォルトスタックサイズを減らした
画像あぼーん実装
履歴右クリックでポップアップ表示して特定の履歴を削除出来るようにした
Res.htmlにNAMELINKを追加(「名前」に置換する)
IDあぼーんしたら板の方にも自動で登録するようにした
タブ右クリックメニューの複数のタブを閉じる機能をまとめた
スレ一覧とスレビューのツールバー表示/非表示設定追加
板一覧とスレ一覧のテキストカラー変更設定追加
板一覧とスレ一覧の偶数行の色設定追加
画像ポップアップのマージン設定追加( jd.css の .imgpopup の margin )
サイドバーの表示切り替えの挙動がおかしかった問題を修正
bbsmenu.htmlの解釈がおかしかった問題を修正
スレのプロバティの番号あぼーんでマイナスの数を入れると落ちるバグを修正
スレのプロバティの番号あぼーんで12-34のような書式に対応した
</release>

<release version="1.9.5-beta070528" date="2007/05/28(月)">
右ペーンが空の時にサイドバーを最大化する設定(expand_sidebar)追加
ポップアップと画像カーソルの間のマージン設定(margin_imgpopup)追加
スレビューの削除メニューなどに「削除して再読み込み」を追加
スレを再読み込みして再起動するとスレ一覧の新着がマイナスになる問題を修正
水平タブ(0x09)が文字化けする問題を修正
スレビューで上下キーのスクロール速度を調整可能にした( key_scroll_size )
スレ内で検索をしたときにヒット数を表示するようにした
configureのオプションに--with-migemodictを追加
検索用補完Entryクラス実装
最近閉じたスレの履歴を実装
設定にプライバシーメニュー追加
</release>

<release version="1.9.5-beta070611" date="2007/06/11(月)">
XML処理の変更に伴い、*.xmlファイルの書式をXMLの仕様に従うように変更
BackspEditコントロール設定を追加
書き込みビューに最終書き込み日を表示
連続書き込み規制(書き込みビューに再書き込み可能になるまでの時間を表示)
スレビューで再読込ボタンで全タブを更新する機能追加( reload_allthreads )
JD ホームページのアドレスを設定できようにした( url_jdhp )
画像の横幅や縦幅が長い場合に落ちるバグを修正
画像のファイルサイズが0byteの時に画像ビューが落ちるバグを修正
AAメニューの履歴数を変更できるようにした( aahistory_size )
</release>

<release version="1.9.5-beta070616" date="2007/06/16(土)">
bbsmenu.html内にあるリンクは全て板とみなす設定追加( use_link_as_board )
アニメーションGIFの表示処理を軽減化
</release>

<release version="1.9.5-rc070625" date="2007/06/25(月)">
メール指定が無いときの名前欄の文字色を選択できるようにした
画像まわりの細かいバグをまとめて修正した
</release>

<release version="1.9.5-070630" date="2007/06/30(土)">
AAメニューでカーソル上下で誤動作するバグを修正
</release>

<release version="1.9.6-beta070804" date="2007/08/04(土)">
更新チェック機能実装
更新チェックのタイムアウト値の設定追加(loader_timeout_checkupdate)
スレが壊れているときにラベルの色を赤くするようにした
スレ一覧のポップアップが表示されないときがあるバグを修正
お気に入りでディレクトリ以外の行でも左キーで開いているフォルダを畳めるようにした
migemo検索の高速化パッチを適用
スレ一覧でインクリメンタル検索が出来るようにした ( inc_search_board = 1 )
メニュー項目でダイアログを開く行に「...」を付けるパッチを当てた
板を開いたまま再起動時するとSETTING.TXTを勝手にロードするバグを修正
SETTING.TXTの取得時に更新時刻を送るようにした
板のプロパティにローカルルールを表示
画像ビュアーで302の画像もダウンロードするようにした
画像のボタン設定追加(CloseImageButton,ScrollImageButton,CancelMosaicButton)
画像の拡張子と実際の形式が違うときはモザイク解除の時に警告するようにした
</release>

<release version="1.9.6-beta070918" date="2007/09/18(火)">
スレ一覧の表示項目を設定できるようにした
非アクティブのときに書き込みウィンドウを折り畳むようにした
GNOME環境でウィンドウを閉じたときに最大化が時々勝手に解除されるバグを修正
各ビューで全て選択(Ctrl+a)実装
書き込みビューのコンテキストメニューにAA入力の項目を追加
書き込みビューを閉じるときに編集中の文章を保存できるようにした
画像あぼーんの情報を削除できるようにした
画像ウィンドウでお気に入り追加ダイアログを開くとウィンドウが畳まれるバグを修正
アンカーのコンテキストメニューでジャンプが動作しなくなっていたバグを修正
全お気に入り更新チェックを追加
メインメニューに「ツール」の項目を追加
履歴メニューの項目もEnterキーを押してアクティブに出来るようにした
aboutダイアログ追加( パッチスレ71 )
button.confでDbl*の設定が効かなかったバグを修正
スレ一覧のログ検索ボタンを削除してツールメニューにログ検索移動
発言数のチェックを外すオプション追加( check_id = 1 )
スレをお気に入りに登録したときに自動でブックマーク設定するようにした
レス参照で色を変える回数を設定できるようにした( num_reference_high=3, num_reference_low=1 )
発言数で色を変える回数を変更できるようにした( num_id_high=4, num_id_low=2 )
画像のピクセル数が大きいときは警告するようにした( max_img_pixel = 20 )
タブのロック機能を実装
メインメニューからJDホームページの項目を削除(aboutダイアログから可能)
書き込みビューのコンテキストメニューに「クリップボードから引用」の項目を追加
書き込みビューのコンテキストメニューに「JDの動作環境を記入」の項目を追加
バージョン表示でSVN版のリビジョン番号を表示できるようにした
スレの再取得をするときにあぼーんなどのスレ情報を削除しないようにした
スレがDAT落ちしているときにラベルの色を青くするようにした
設定メニューに板、スレ、画像プロパティ項目追加
タブメニューに「プロパティ」追加
表示設定からタブの非表示が出来るようにした
</release>

<release version="1.9.6-rc070930" date="2007/09/30(日)">
お気に入りで新規ディレクトリの追加が出来なかったバグを修正
板一覧とお気に入りで前検索すると固まることがあるバグを修正
</release>

<release version="1.9.6-071005" date="2007/10/05(金)">
書き込みメッセージを保存した際にダイアログが再び出てしまうバグを修正
ログ検索中にビューを閉じても検索スレッドが停止しないバグを修正
</release>

<release version="1.9.7-beta071101" date="2007/11/01(木)">
BMP画像表示に対応
スレタイ検索機能実装( menu_search_title, url_search_title, regex_search_title )
BEログイン実装
BEのマーク表示をするようにした
メインツールバーと各ビューのツールバーの項目を編集出来るようにした
起動、シャットダウンを高速化した
板一覧を開くときにリダイレクトされたら移転のチェックをするようにした
メインメニューにキーアクセラレータとショートカットを追加
「JDの動作環境」の一部に「/etc/issue.net」値を取得して表示するようにした
書き込みプレビューでURLに含まれる「&amp;」が「&amp;amp;」と表示されてしまう問題を修正
「IPv6使用」設定をメニューに追加
</release>

<release version="1.9.7-beta071109" date="2007/11/09(金)">
「画像ポップアップを表示する」設定を追加
スレビューでリロード後に末尾に飛ぶ設定を追加( jump_after_reload )
スレビューの検索に「WEB検索」を追加( menu_search_web, url_search_web )
画像ビューを開いたまま閉じて再起動するとビューが展開されずに落ちるバグを修正
起動中やスレ表示前にスレビューの上をマウス移動すると落ちるバグを修正
ツールバー(リスト)項目設定のダイアログを充実させた
画像関係の表示メニューを設定メニューから表示メニューに移した
</release>

<release version="1.9.7-rc071115" date="2007/11/15(木)">
画像ビューのメニュー項目の一部にマウスジェスチャが表示されていなかったバグを修正
板一覧にフォーカスがあるときに板一覧再読み込みするとサイドバーが閉じるバグを修正
起動時にjd.confが読み込めない時はjd.confが存在するか確認するようにした
スレビューで他スレをポップアップ表示したあとキャッシュ削除してもポップアップ表示されるバグを修正
「画像を全て保存」でモザイクを外していない画像まで保存していた問題を修正
お気に入りで ディレクトリを削除するとキーボードフォーカスが外れるバグを修正
</release>

<release version="1.9.7-071122" date="2007/11/22(木)">
configureに --with-athlon64 オプションを追加
$LANGが取得出来なかった場合に落ちるバグを修正
SVN版で作業コピーでない場合にコンパイル出来なくなっていたバグを修正
</release>

<release version="1.9.8-beta071210" date="2007/12/10(月)">
RH系のブラウザをhtmlviewからxdg-openに変更した
メッセージダイアログでtabでラベルにフォーカスが移るバグを修正
リロード後に新着に自動的に移動する設定追加( jump_new_after_reload )
key.confに Scroll*Board と Scroll*Image を追加
起動時に画像ウィンドウも復元するとスレビューが表示されなかったバグを修正
スレビューでn,pで前後のレスに移動できるようにした
書き込みビューのファイル選択画面でキャンセルを押すとビューが閉じるバグを修正
ログ検索中に他の検索ビューを閉じると検索が終了するバグを修正
タブを中クリックで閉じる動作をキャンセルできるようにした
ポップアップフレームとオートスクロールマーカの色を設定できるようにした
お気に入りの最終行がディレクトリの時に最終行へのジャンプが正常に動作しないバグを修正
リンクの上でコンテキストメニューを開いてからマウスを移動してクリックするとリンクが開くバグを修正
デフォルトではOpenSSLではなくてGNUTLSを使用するようにした( --with-openssl でOpenSSL使用 )
テーマを変更したときにスレビューのラベルの背景色が変わらなかったバグを修正
</release>

<release version="1.9.8-beta071218" date="2007/12/18(火)">
テーマによってはLabelEntryの背景色が変になるバグを修正
dat落ちしたスレを開いたとき、タブに「???」と表示するようにした
ウィンドウのリサイズ直後にスレの範囲選択の位置がズレる時があったバグを修正
レスにUTF-8直書きされているときにスレが壊れていると判定されるバグを修正
スレの連鎖あぼーん設定のチェックが再起動すると外れるバグを修正
テーマによってはタブの色が変になるバグを修正
</release>

<release version="1.9.8-rc071223" date="2007/12/23(日)">
テーマによってはLabelの背景色が変になるバグを修正
バージョン2.4のgtkmmでビルド出来なかった問題を修正
旧設定ファイル(.jdrc)が存在するとキャッシュディレクトリが出来ない時があるバグを修正
</release>

<release version="1.9.8-071228" date="2007/12/28(金)">
お気に入りでアイテムが消えない時があったバグを修正
</release>

</document>

=== JDimproved/JDim/xml/urlreplace.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="URL変換について">


<group header="URL変換">
  <sentence>
    書き込みされたURLと実際に表示する画像のURLが異なる場合に、URLを正規表現で変換することで
    直接画像にアクセスできる。
    また、リファラを送信したり、拡張子のないURLを強制的に画像と認識させることができる。
  </sentence>
</group>


<group header="設定ファイル">
  <sentence>
    URL変換機能を使う場合は、キャッシュディレクトリの「urlreplace.conf」ファイルに設定する。
    設定ファイルを変更したあとは、一度JDを再起動することで設定内容が有効になる。
  </sentence>

  <sentence>
    youtubeのサムネイルをインライン画像として表示するための変換が、デフォルトで設定される。
    なお、設定内容をリセットしたい場合は、「urlreplace.conf」ファイルを削除してからJDを起動すると、
    ファイルが自動で再作成される。
  </sentence>

<example caption="設定ファイルの書式">
正規表現&lt;タブ&gt;変換後URL&lt;タブ&gt;リファラURL&lt;タブ&gt;制御文字
</example>

  <sentence>
    制御ファイルに指定した、正規表現はファイルの先頭から順に評価される。
    また、リファラURLおよび制御文字は、変換した後のURLが、正規表現に一致したときに有効になる。
  </sentence>

<subgroup header="変換後URLおよびリファラURL">
  <sentence>
    正規表現に一致した文字列をもとに、以下の置換文字を使用できる。
  </sentence>
  <descriptions>
    <item header="\0 または $0">正規表現にマッチした文字列</item>
    <item header="\1〜\9 または $1〜$9">正規表現で「(...)」にマッチした部分文字列</item>
  </descriptions>
</subgroup>

<subgroup header="制御文字">
  <descriptions>
    <item header="$IMAGE">
      拡張子がない場合でも画像として扱う。
    </item>
    <item header="$BROWSER">
      拡張子があっても画像として扱わない。
    </item>
    <item header="$GENUINE">
      JDは拡張子と実際の画像形式が不一致のときに、画像が偽装されていると判断して
      モザイクで表示する。これを指定すると、拡張子の偽装をチェックせず、モザイクで表示しない。
    </item>
    <item header="$BREAK">
      正規表現に一致したら以降の判定を行わず、評価を終了する。
    </item>
    <item header="$THUMBNAIL">
      変換した後のURLが、動画投稿サイトなどのサムネイル画像として扱う。
      画像表示設定でインライン画像を表示しているときに有効となる。
    </item>
  </descriptions>
</subgroup>

</group>


<group header="設定例">
  <sentence>
    リファラURLを送信したり制御文字を有効にするには、変換後URLが正規表現に一致するように表現する。
    変換後のURLを変換用の条件とリファラ用の条件を、2行に分けて書いてもよい。
  </sentence>

<example caption="1行でまとめて書く場合">
http://www\.foobar\.com/(view/|img\.php\?id=)([0-9]+)	http://www.foobar.com/view/$2	$0	$IMAGE
</example>

<example caption="2行に分けて書く場合">
http://www\.foobar\.com/img\.php\?id=([0-9]+)	http://www.foobar.com/view/$1
http://www\.foobar\.com/view/([0-9]+)	$0	$0	$IMAGE
</example>

</group>

</document>

=== JDimproved/JDim/docs/xml/environment.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="動作環境の記入について">


<group header="概要">
  <sentence>
  書き込みビューのコンテキストメニューからJDの動作環境が記入できる。不具
  合報告などの際に活用すること。
  </sentence>

<asciiart caption="自動的に入力される物の例">
[バージョン] 2.0.3-090305
[ディストリ ] Example Linux
[パッケージ] バイナリ/ソース( &lt;配布元&gt; )
[ DE／WM ] GNOME
[　gtkmm 　] 2.14.3
[　glibmm 　] 2.18.1
[オプション ] '--with-alsa'
[ そ の 他 ]
</asciiart>

  <sentence>
  バージョン等は自動で入力されるが、他の項目については追加/変更すること。
  </sentence>
</group>


<group header="注意">
  <list type="circle">
    <item>「[パッケージ]」の項目に自動で表示される物はテンプレートなので明らかに不要と考えられる場合を除いて変更する事。</item>
    <item>「[ DE／WM ]」の項目は環境変数から判別出来た場合のみ入る。</item>
    <item>「[オプション ]」の項目はconfigureオプションの一部が入る。</item>
    <item>SVN版のバージョンはビルド時にリビジョン番号が取得できた場合にはそれになるが、そうでない場合は日時形式になる。</item>
    <item>makeはソースのルートディレクトリ(top_builddir)で実行しないとリビジョン番号が取得/更新されないので注意。</item>
  </list>
</group>


<group header="記載例">

<asciiart>
[バージョン] 2.0.3-090305
[ディストリ ] Ubuntu 8.10
[パッケージ] バイナリ( Ubuntu-ja )
[ DE／WM ] GNOME
[　gtkmm 　] 2.14.1
[　glibmm 　] 2.18.1
[オプション ]
[ そ の 他 ]
</asciiart>

<asciiart>
[バージョン] 2.0.3-090305
[ディストリ ] Fedora release 10 (Cambridge)
[パッケージ] ソース( Fedora SRPM )
[ DE／WM ] KDE + compiz-0.7.8
[　gtkmm 　] 2.14.3
[　glibmm 　] 2.18.1
[オプション ] '--with-sessionlib=gnomeui'
[ そ の 他 ]
</asciiart>

<asciiart>
[バージョン] SVN Rev.2701
[ディストリ ] Gentoo Base System release 1.12.11.1( x86_64 )
[パッケージ] ソース( JD project )
[ DE／WM ] fluxbox
[　gtkmm 　] 2.14.3
[　glibmm 　] 2.18.1
[オプション ] '--with-alsa'
'--eneble-gprof'
[ そ の 他 ] ebuild 使用
</asciiart>

</group>


</document>

=== JDimproved/JDim/docs/xml/usrcmd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="main.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="ユーザーコマンド、リンクフィルタについて">


<group header="登録">
  <sentence>
  スレビューや画像ビューで右クリックしたときに表示されるコンテキストメニューにユーザ
  コマンドを登録できる。
  </sentence>

  <sentence>
  登録するにはメニューの「設定」→「その他」→「ユーザコマンドの編集」か
  ら設定ダイアログを開き、右クリックしてコンテキストメニューから「新規コ
  マンド」を選択する。同様にディレクトリや区切り線も作成できる。
  </sentence>

  <sentence>
  「選択不可のユーザコマンドを非表示にする」をチェックすると選択出来ない
  コマンドは表示されなくなる。
  </sentence>
</group>


<group header="編集">
  <sentence>  
  一度設定したコマンドを編集する場合は、設定ダイアログで対象のコマンドを
  ダブルクリックする。また、行をドラッグして位置を変えたり階層構造にする
  ことが出来る。行を削除する場合はクリックしてからdeleteキーを押すかコン
  テキストメニューから削除する。
  </sentence>

  <sentence>
  なお、実行するコマンドでは下記のような置換文字列を指定出来る。また、コ
  マンドを手動で編集したい場合はキャッシュディレクトリにある&quot;usrcmd.xml&quot;
  というXMLファイルを編集する。
  </sentence>
</group>


<group header="置換文字一覧">
  <sentence>
  ユーザコマンドの具体的な使いかたは <text link="http://sourceforge.jp/projects/jd4linux/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E8%A8%AD%E5%AE%9A%E9%9B%86">ユーザーコマンド設定集</text> (wiki) を参照すること。
  </sentence>

  <sentence>
   以下の説明はスレビューでユーザーコマンドを使用する場合であるので、画像ビューで使用する場合は $URL 等は画像が貼ってあったスレのアドレス、$LINK 等は画像のアドレス、$CACHEDIMG は画像キャッシュのパスに読み替える。
  </sentence>

  <descriptions>
    <item header="$VIEW">ネットワーク設定で指定されたwebブラウザで開く ( 例: $VIEW $LINK でリンクをブラウザで開く )</item>
    <item header="$DIALOG">$DIALOGの後の文字列をダイアログ表示</item>
    <item header="$ONLY">スレのURLが$ONLYの後の文字列(正規表現)を含む時だけメニューを表示(下記参照)</item>
    <item header="$URL">スレのURL ( 例: http://hibari.2ch.net/test/read.cgi/linux/1276299375/ )</item>
    <item header="$DATURL">サーバー上のdatファイルのURL ( 例: http://hibari.2ch.net/linux/dat/0123456789.dat )</item>
    <item header="$SERVER">http://などのプロトコルを含むスレのURLから取り出したサーバー名 ( 例: http://hibari.2ch.net )</item>
    <item header="$HOSTNAME">http://などのプロトコルを除くスレのURLから取り出したサーバー名 ( 例: hibari.2ch.net )</item>
    <item header="$HOST">$HOSTNAMEと同じ</item>
    <item header="$OLDHOSTNAME">$HOSTNAMEと同じだが、もしスレが板移転前に立てられたものなら移転前のサーバー名を使用する</item>
    <item header="$OLDHOST">$OLDHOSTNAMEと同じ</item>
    <item header="$BBSNAME">スレが属する板のID ( 例: http://hibari.2ch.net/linux なら linux )</item>
    <item header="$DATNAME">スレのID ( 例: http://hibari.2ch.net/test/read.cgi/linux/1276299375/ なら 1276299375 )</item>
    <item header="$LINK">マウスの下にリンクがあればそのURL</item>
    <item header="$SERVERL">http://などのプロトコルを含むリンクから取り出したサーバー名( 例: http://www.google.co.jp )</item>
    <item header="$HOSTNAMEL">http://などのプロトコルを除くリンクから取り出したサーバー名( 例: www.google.co.jp )</item>
    <item header="$HOSTL">$HOSTNAMELと同じ</item>
    <item header="$OLDHOSTNAMEL">$HOSTNAMELと同じだが、もしリンク先が2chのスレの場合は板移転前のサーバー名を使用する</item>
    <item header="$OLDHOSTL">$OLDHOSTNAMELと同じ</item>
    <item header="$BBSNAMEL">もしリンク先が2chのスレの場合は、そのスレが属する板のID ( 例: http://hibari.2ch.net/linux なら linux )</item>
    <item header="$DATNAMEL">もしリンク先が2chのスレの場合は、そのスレのID ( 例: http://hibari.2ch.net/test/read.cgi/linux/1276299375/ なら 1276299375 )</item>
    <item header="$CACHEDIMG">リンクが画像でかつキャッシュされている時は画像キャッシュの場所</item>
    <item header="$LOGPATH">キャッシュディレクトリの場所 ( 例: ~/.jd/ )</item>
    <item header="$LOCALDAT">キャッシュディレクトリにあるdatファイルの場所 ( 例: ~/.jd/hibari.2ch.net/linux/1276299375.dat )</item>
    <item header="$LOCALDATL">もしリンク先が2chのスレの場合は、キャッシュディレクトリにあるdatファイルの場所</item>
    <item header="$TITLE">スレのタイトル(UTF-8)</item>
    <item header="$NUMBER">スレビューの場合はマウスカーソルの下にあるレス番号、画像ビューの場合は参照元のレス番号</item>
    <item header="$BOARDNAME">スレが属する板の名前(UTF-8)</item>
    <item header="$TEXT">範囲選択した文字列(UTF-8)</item>
    <item header="$TEXTI">範囲選択した文字列(UTF-8)、選択がないときは入力ダイアログを表示する</item>
    <item header="$TEXTU">範囲選択した文字列(UTF-8)をURLエンコード</item>
    <item header="$TEXTIU">範囲選択した文字列(UTF-8)をURLエンコード、選択がないときは入力ダイアログを表示する</item>
    <item header="$TEXTX">範囲選択した文字列をEUCに変換してURLエンコード</item>
    <item header="$TEXTIX">範囲選択した文字列をEUCに変換してURLエンコード、選択がないときは入力ダイアログを表示する</item>
    <item header="$TEXTE">範囲選択した文字列をSJIS(MS932)に変換してURLエンコード</item>
    <item header="$TEXTIE">範囲選択した文字列をSJIS(MS932)に変換してURLエンコード、選択がないときは入力ダイアログを表示する</item>
    <item header="$INPUT">入力ダイアログを表示(UTF-8)</item>
    <item header="$INPUTU">入力ダイアログを表示してURLエンコード(UTF-8)</item>
    <item header="$INPUTX">入力ダイアログを表示しEUCに変換してURLエンコード</item>
    <item header="$INPUTE">入力ダイアログを表示しSJIS(MS932)に変換してURLエンコード</item>
  </descriptions>

  <subgroup header="$ONLYの例">
    <sentence>
    以下のように設定すると、スレのURLにlinuxを含むときのみメニューに表示
    されて「Linux」とダイアログ表示する。
    </sentence>

    <dialog>
      <item label="コマンド名" value="linuxのみ" />
      <item label="実行するコマンド" value="$ONLY linux $DIALOG Linux" />
    </dialog>

    <sentence>
    以下のコマンドはスレのURLにnewsを含むときのみメニューに表示されて
    「ニュース」とダイアログ表示する。
    </sentence>

    <dialog>
      <item label="コマンド名" value="newsのみ" />
      <item label="実行するコマンド" value="$ONLY news $DIALOG ニュース" />
    </dialog>
  </subgroup>
</group>


<group header="リンクフィルタ">
  <sentence>
  スレビューでリンクをクリックした時、アドレス毎にフィルタリングを行って
  動作を変えることが出来る。アドレスは正規表現として解釈され、フィルタの
  上の方からマッチングしていく。
  </sentence>

  <subgroup header="設定と編集">
    <sentence>
    フィルタの条件を設定するにはメニューの「設定」→「その他」→「リンク
    フィルタの編集」から設定ダイアログを開き、追加ボタンを押してアドレス
    と実行するコマンドを指定する。一度設定した条件を編集する場合は対象の
    条件をダブルクリックする。削除する場合は対象の条件をクリックしてから
    deleteキーを押すか削除ボタンを押す。
    </sentence>

    <sentence>
    順番を変えるには行を選択してから上端ボタンや上へボタンなどを押す。
    コマンドには上のユーザコマンドと同じ置換文字を使える。
    また、リンクフィルタのコマンドでは以下の置換文字を使用できる。
      <descriptions>
        <item header="\0">アドレスの正規表現にマッチした文字列</item>
        <item header="\1〜\9">アドレスの正規表現で「(...)」にマッチした部分文字列</item>
      </descriptions>
    </sentence>

    <sentence>
    なお、コマンドを手動で編集したい場合はキャッシュディレクトリにある
    「linkfilter.xml」というXMLファイルを編集する。
    </sentence>
  </subgroup>

  <subgroup header="使用例">
    <sentence>
    以下のように設定すると hoge.net のjpg画像はeogで開くが、その他のhoge.net
    上にある画像やファイルは外部ブラウザで開く。
    </sentence>

    <dialog>
      <item label="アドレス" value="http://hoge\.net/.*jpg$" />
      <item label="実行するコマンド" value="eog $LINK" />
    </dialog>

    <dialog>
      <item label="アドレス" value="http://hoge\.net/" />
      <item label="実行するコマンド" value="$VIEW $LINK" />
    </dialog>

    <sentence>
    また、以下ではパスにburakuraを含むリンクをクリックすると「ブラクラ」
    というダイアログを表示する。どの条件にもマッチしなかった場合は通常の
    動作になる。
    </sentence>

    <dialog>
      <item label="アドレス" value="burakura" />
      <item label="実行するコマンド" value="$DIALOG ブラクラ" />
    </dialog>
  </subgroup>
</group>


</document>

=== JDimproved/JDim/xml/2009.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="history.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="更新履歴(2009年)">

<release version="2.1.1-beta090128" date="2009/1/28(水)">
お気に入りの編集に対するUNDOとREDOを実装した
お気に入り編集ウィンドウに検索窓を付けた
書き込みしたレスに&quot;が含まれていると鉛筆マークが付かないバグを修正
p2経由で書き込みをチェックしてもbbspink.comではブラウザが開かないバグを修正
</release>

<release version="2.2.0-090212" date="2009/2/12(木)">
キャッシュのsubject.txtが古いと次スレのリンクをクリックした時にdat落ちになるバグを修正
キャッシュのsubject.txtが無いと次スレのリンクをクリックした時にloading表示が消えないバグを修正
キャッシュのsubject.txtが無い時に次スレのリンクをクリックした時のスレタイ類似度計算に
レーベンシュタイン距離を使うようにした
次スレ移行時にお気に入りの名前が編集されているときは新スレの名前にしないようにした
書き込み時にWAVE DASH 問題のため書き込みマークが付かない問題を修正
「スレ情報を消さずにスレ再取得」でタブのロックが外れるバグを修正
「スレ情報を消さずにスレ再取得」でタブの位置がズレるバグを修正
</release>

<release version="2.3.0-090305" date="2009/3/05(木)">
したらばに書き込めなくなった問題に対応( application/x-www-form-urlencoded )
まちBBSの仕様変更に対応 ( read.pl -> read.cgi )
スレタイの先頭がスペースで始まっている場合にスレ一覧で先頭のスペースが省略表示されるバグを修正
タブが含まれる書き込みで鉛筆マークが付かないバグを修正
gtkrcでnotebookのythicknessを0にしてスレ一覧を開くとCPUが100%になるバグを修正
他のビューにタブをドロップするとタブ移動の矢印が消えなかったバグを修正
画像ダウンロード中のツールチップの文字色をスレビューの文字色と合わせた
サイドバーに「お気に入り更新チェックしてタブで開く」ボタンを追加出きるようにした
web検索のショートカットキーを追加 (Ctrl+k)
スレタイ検索のショートカットキーを追加( Ctrl+t)
ローカルログ検索のショートカットキーを追加( Ctrl+Enter )
全ログ検索のショートカットキーを設定出きるようにした( デフォルト無効 )
about:configに「Ctrl+qでウィンドウを閉じない」を追加
</release>

<release version="2.4.0-beta090429" date="2009/4/29(水)">
スレのプロパティのあぼーん設定に「sage以外あぼーん」を追加
まちBBSのサブジェクトをtitleタグから取得するようにした( offlawモードでない時 )
まちBBSのofflaw.cgi読み込みモードを実装( 設定メニューの一般項目で設定)
動作環境のconfigureオプションとして表示する内容を一部に限定した
p2にログインして直接書き込みできるようにした
鬼車使用時に改行が入ると正規表現のマッチングに失敗する問題を修正
about:configに画像のスムージングレベルの設定を追加
datファイルのインポート機能を実装
datファイルの一時表示機能を実装
JBBSの文字コードをEUC-JPからEUCJP-WINに変更(丸付き数字の文字化け対策)
次スレ移行時に古いスレタイが新スレタイに変わらない時があるバグを修正
16進数の文字参照を実装
スレ一覧更新時にDat落ちしたスレをスレッドあぼーんのリストから取り除ける様にした(ダイアログ表示)
まちBBSのトップページをWebブラウザで開く事が出来ない問題を修正
フォント幅の計算時にメモリの割り当て領域外にアクセスする場合があったバグを修正
板(スレ一覧)の更新チェック機能を実装
タブ切り替えボタンをタブの右側に追加
</release>

<release version="2.4.0-beta090510" date="2009/5/10(日)">
gtk+-2.4辺りのバージョンのgtkを使用するとスレビューのツールバーのボタンが押せないバグを修正
ハッシュの導入によるDBTREE::BoardBase::get_article関数の高速化
configureオプションに「--with-native」を追加(gcc>=4.2, x86 or x86_64)
スレビューの描画領域の高さが1以下の時にスレの読み込みをすると落ちるバグを修正
-s ( --skip-setup ) 起動オプション追加
</release>

<release version="2.4.0-rc090516" date="2009/5/16(土)">
スレにフォントに含まれない文字がある時にコンソールに大量のエラーが表示される問題を修正
Dat落ちしたスレの更新可能アイコン表示が消えないバグを修正
3ペーン表示時にタブをクリックしてもスレ一覧とスレビュー間のフォーカスが移らないバグを修正
3ペーン表示時にタブ上でホイールを回転してもスレ一覧とスレビュー間のフォーカスが移らないバグを修正
タブ切り替えボタンでタブを切り替えたときにスレタイやステータスが変わらないバグを修正
タブメニューの移動サブメニューでタブを切り替えたときにスレタイやステータスが変わらないバグを修正
</release>

<release version="2.4.0-090522" date="2009/5/22(金)">
細かいバグをいくつか修正
</release>

<release version="2.4.1-beta090628" date="2009/6/28(日)">
水平線(HR)の左端をテキストの字下げ位置に合わせた
スレ一覧でキャッシュが無いスレは「dat保存」メニューを選択できないようにした
datファイルのサイズ表記を k から K に変更
画像メニューに「エラー画像を閉じる」を追加(パッチ124)
jd.confの設定値が異常な場合の安全策を追加
現在表示中のタブの表示が変(右端が切れる時がある)な問題を修正
タブ上でのホイール回転でタブを循環表示するようにした
タブ切り替えボタンの枠がフォーカス時にはみ出るバグを修正
ローダの仕様を変更(詳しくはJDスレ7-613参照)
表示位置でタブを選択出来るキーバインドを追加
win32対応
スレビューの画像ポップアップメニューに「モザイクで開く」を追加
書き込みプレビューで新方式のトリップに対応
画像ポップアップ表示時にポインタがポップアップと重なるとポップアップが消えるバグを修正
</release>

<release version="2.4.1-090712" date="2009/7/12(日)">
タブ切り替えメニューにタブのアイコンを表示
お気に入りの次スレ自動更新時に確認ダイアログを表示するようにした
表示メニュー→詳細→一般に「ツールバーの背景を描画する」を追加
</release>

<release version="2.4.2-beta090806" date="2009/08/06(木)">
板一覧の更新時にエラー等で新規データが空になった場合でも更新されてしまう問題を修正
サイドバーのアイコン表示切り替えアルゴリズムを効率化
サイドバーの項目をクリックしてもアイコン表示が戻らない時があったバグを修正
サイドバーの更新チェックのキャンセルが効かなかったバグを修正
サイドバーに履歴ビューを実装
サイドバーの更新チェック機能を改良
履歴メニューを改良
スレ一覧の!のソートモードにモード3を追加
スレビューのコンテキストメニューの項目を編集できるようにした
スレビューのコンテキストメニューに「再読み込み」を追加
スレビューのコンテキストメニューに「タイトルとURLをコピー」を追加
スレビューのコンテキストメニューに「お気に入りに追加」を追加
ツールバー項目設定の「元に戻す」ボタンを押してもデフォルト状態に戻らない問題を修正
レスポップアップで行数の少ないレスでもスクロールさせないと全文が読めないバグを修正
</release>

<release version="2.4.2-beta090914" date="2009/09/14(月)">
書き込みビューにスペースと&amp;nbsp;を相互に変換する機能を追加
スレ一覧でツールバー非表示の時にCtrl+fや/で検索バーを表示できるようにした
画像ビューにユーザコマンドメニューを追加
スレビューのコンテキストメニューに「選択範囲のレスをあぼ〜ん」を追加
DAT落ちしたスレを開いた時にダイアログを表示するようにした
タブメニューの移動の項目にアイコンを表示するようにした
スレ一覧でスレを複数指定してからDatの保存が出来るようにした
subject.txtのレス数よりも実際のレス数が多い時スレ一覧にアイコンを表示するようにした
スレ一覧で!を押したときに現在のソートのモードをステータスバーに表示するようにした
更新済タブへ移動のショートカットキーとマウスジェスチャ(デフォルト未設定)を追加
</release>

<release version="2.4.2-090927" date="2009/09/27(日)">
画像ビューが埋め込み表示の時にビューを開くとスレビューのスクロール位置がズレる問題を修正
</release>

<release version="2.5.0-beta091103" date="2009/11/3(火)">
書き込みビューが空のときに対応するスレを閉じたら書き込みビューも閉じるようにした
スレ一覧の since、最終書込の表示形式を表示メニューから変更できるようにした
画像ポップアップ上でショートカットキーを使えるようにした
画像ポップアップ上でマウスジェスチャを使えるようにした
画像ポップアップ上でコンテキストメニューを表示できるようにした
フォントと色の詳細設定をタブで分けた
色の詳細設定に「スレビューの選択範囲の色設定に gtkrc を用いる」を追加
色の詳細設定にabout:configから「ツリービューの背景色設定に gtkrc を用いる」を移動
色の詳細設定で複数行を選択可能にした
about:configに「起動時にお気に入りを自動でチェックする」を追加
HTML化された過去ログの読み込みに対応
コンテキストメニューの表示がキャンセルされるとポップアップが消えなくなるバグを修正
画像ビューでタブスクロールボタンを押すとキーボードフォーカスが外れるバグを修正
スレを閉じるときに無駄なディスクアクセスが生じていた問題を修正
スレ一覧の列幅を調整するときに時々一番上のスレを開くバグを修正
ログ一覧の表示機能を実装
</release>

<release version="2.5.0-beta091123" date="2009/11/23(月)">
更新チェック中に対象スレを手動でロードすると更新チェックが停止する時があるバグを修正
お気に入り追加ダイアログで名前を変更してもお気に入りに反映されないバグを修正
板一覧再読み込みで更新量が多いと固まったようになるバグを修正
画像ローダのメモリキャッシュ機能を実装(デフォルトキャッシュ数 3 )
</release>

<release version="2.5.0-091206" date="2009/12/06(日)">
初回起動時のデフォルトフォント候補に小夏フォントを追加
エラーなどのメッセージがファイルに出力される機能を起動オプションとして追加
</release>

<release version="2.5.5-beta091220" date="2009/12/20(日)">
スレ一覧でスレッド924(お知らせスレ)をアイコン表示するようにした
スレビューでIDの重複数のカウント処理を高速化した
スレビューで描画処理を少しだけ最適化した
スレ一覧の読み込みと表示処理を改良した
HTTP201の画像を開けないバグを修正
about:configに「ビューを閉じても書き込み欄の日本語のON/OFF状態を保つ」を追加
p2のログイン処理の仕様変更に対応 ( submit_member -> submit_userlogin )
キャッシュの画像の読み込みに失敗すると画像表示が乱れるバグを修正
</release>

<release version="2.5.5-rc091225" date="2009/12/25(金)">
about:configに「スレ一覧をロードする前にキャッシュにある一覧を表示する」を追加
about:configに「お知らせスレ(924)のアイコンを表示する」を追加
色の詳細設定でデフォルトと異なる設定の行の背景色を変えるようにした
about:configの「true」「false」を「はい」「いいえ」表記に変更
書き込み履歴のあるスレを削除する時はダイアログで問い合わせるようにした
</release>

<release version="2.5.5-091228" date="2009/12/28(月)">
書き込み履歴のあるスレを削除する時の確認ダイアログを非表示に出来るようにした
</release>

</document>

=== JDimproved/JDim/docs/xml/history.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="history.xsl"?>
<!DOCTYPE document SYSTEM "document.dtd">

<document header="更新履歴">


<history>
  <year>2015</year>
  <year>2014</year>
  <year>2013</year>
  <year>2012</year>
  <year>2011</year>
  <year>2010</year>
  <year>2009</year>
  <year>2008</year>
  <year>2007</year>
  <year>2006</year>
</history>


</document>
